# Generated by Django 2.1.5 on 2019-02-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
